package Vistas;
import javax.swing.JDesktopPane;

public class FrmPrincipal extends  javax.swing.JFrame {
    public GestorVistaPrincipal gestorVista;
    
    public GestorVistaPrincipal getGestorVista() {
        return gestorVista;
    }

    public void setGestorVista(GestorVistaPrincipal gestorVista) {
        this.gestorVista = gestorVista;
    }
    public FrmPrincipal() {
        initComponents();
    }

    public FrmPrincipal(GestorVistaPrincipal aThis) {
        initComponents();
        gestorVista=aThis;
    }


    public JDesktopPane getEscritorio() {
        return escritorio;
    }

    public void setEscritorio(JDesktopPane escritorio) {
        this.escritorio = escritorio;
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        Marca = new javax.swing.JButton();
        Auto = new javax.swing.JButton();
        Modelo = new javax.swing.JButton();
        Empleado = new javax.swing.JButton();
        Cliente = new javax.swing.JButton();
        ventas = new javax.swing.JButton();
        Pais = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ejemplo");
        setResizable(false);

        escritorio.setPreferredSize(new java.awt.Dimension(1250, 560));

        Marca.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Marca.setText("Marca");
        Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarcaActionPerformed(evt);
            }
        });

        Auto.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Auto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/auto.png"))); // NOI18N
        Auto.setText("Auto");
        Auto.setHideActionText(true);
        Auto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutoActionPerformed(evt);
            }
        });

        Modelo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Modelo.setText("Modelo");
        Modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModeloActionPerformed(evt);
            }
        });

        Empleado.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Empleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empleado.png"))); // NOI18N
        Empleado.setText("Empleado");
        Empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpleadoActionPerformed(evt);
            }
        });

        Cliente.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cliente.png"))); // NOI18N
        Cliente.setText("Cliente");
        Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteActionPerformed(evt);
            }
        });

        ventas.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ventas.png"))); // NOI18N
        ventas.setText("Ventas");
        ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventasActionPerformed(evt);
            }
        });

        Pais.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Pais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pais.png"))); // NOI18N
        Pais.setText(" Pais");
        Pais.setActionCommand("  Pais");
        Pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaisActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo (1).png"))); // NOI18N

        escritorio.setLayer(Marca, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(Auto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(Modelo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(Empleado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(Cliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(ventas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(Pais, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(971, 971, 971)
                .addComponent(Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(971, 971, 971)
                .addComponent(Pais, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(971, 971, 971)
                .addComponent(Auto, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(971, 971, 971)
                .addComponent(Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(Empleado))
            .addComponent(jLabel1)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(138, 138, 138)
                .addComponent(Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(Pais, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Auto, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 1206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarcaActionPerformed
       this.gestorVista.abrirMarca(getEscritorio());
    }//GEN-LAST:event_MarcaActionPerformed

    private void ModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModeloActionPerformed
         this.gestorVista.abrirModelo(getEscritorio());
    }//GEN-LAST:event_ModeloActionPerformed

    private void AutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutoActionPerformed
        this.gestorVista.abrirAuto(getEscritorio());
    }//GEN-LAST:event_AutoActionPerformed

    private void ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteActionPerformed
        this.gestorVista.abrirCliente(getEscritorio());
    }//GEN-LAST:event_ClienteActionPerformed

    private void EmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpleadoActionPerformed
       this.gestorVista.abrirEmpleado(getEscritorio());
    }//GEN-LAST:event_EmpleadoActionPerformed

    private void ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventasActionPerformed
       this.gestorVista.abrirVentas(getEscritorio());
    }//GEN-LAST:event_ventasActionPerformed

    private void PaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaisActionPerformed
        this.gestorVista.abrirPais(getEscritorio());// TODO add your handling code here:
    }//GEN-LAST:event_PaisActionPerformed

public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Auto;
    private javax.swing.JButton Cliente;
    private javax.swing.JButton Empleado;
    private javax.swing.JButton Marca;
    private javax.swing.JButton Modelo;
    private javax.swing.JButton Pais;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton ventas;
    // End of variables declaration//GEN-END:variables

}
